<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
    <PackageReference Include="Swashbuckle" Version="5.6.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CsvDataLoader.Service\CsvDataLoader.Service.csproj" />
    <ProjectReference Include="..\GoldenRaspberryAwards.Core\GoldenRaspberryAwards.Core.csproj" />
    <ProjectReference Include="..\GoldenRaspberryAwards.Infrastructure\GoldenRaspberryAwards.Infrastructure.csproj" />
    <ProjectReference Include="..\GoldenRaspberryAwards.SharedServices\GoldenRaspberryAwards.SharedServices.csproj" />
  </ItemGroup>

</Project>
